package grpc

// Code generated by gowrap. DO NOT EDIT.
// template: ../../templates/grpc.tmpl
// gowrap: http://github.com/hexdigest/gowrap

import (
	"context"

	"go.uber.org/yarpc"

	sharddistributorv1 "github.com/cadence-workflow/shard-manager/.gen/proto/sharddistributor/v1"
	"github.com/cadence-workflow/shard-manager/client/sharddistributor"
	"github.com/cadence-workflow/shard-manager/common/types"
	"github.com/cadence-workflow/shard-manager/common/types/mapper/proto"
)

func (g sharddistributorClient) DrainShards(ctx context.Context, dp1 *types.DrainShardsRequest, p1 ...yarpc.CallOption) (dp2 *types.DrainShardsResponse, err error) {
	response, err := g.c.DrainShards(ctx, proto.FromShardDistributorDrainShardsRequest(dp1), p1...)
	return proto.ToShardDistributorDrainShardsResponse(response), proto.ToError(err)
}

func (g sharddistributorClient) ForceResetNamespace(ctx context.Context, fp1 *types.ForceResetNamespaceRequest, p1 ...yarpc.CallOption) (fp2 *types.ForceResetNamespaceResponse, err error) {
	response, err := g.c.ForceResetNamespace(ctx, proto.FromShardDistributorForceResetNamespaceRequest(fp1), p1...)
	return proto.ToShardDistributorForceResetNamespaceResponse(response), proto.ToError(err)
}

func (g sharddistributorClient) GetDrainedShards(ctx context.Context, gp1 *types.GetDrainedShardsRequest, p1 ...yarpc.CallOption) (gp2 *types.GetDrainedShardsResponse, err error) {
	response, err := g.c.GetDrainedShards(ctx, proto.FromShardDistributorGetDrainedShardsRequest(gp1), p1...)
	return proto.ToShardDistributorGetDrainedShardsResponse(response), proto.ToError(err)
}

func (g sharddistributorClient) GetExecutorState(ctx context.Context, gp1 *types.GetExecutorStateRequest, p1 ...yarpc.CallOption) (gp2 *types.GetExecutorStateResponse, err error) {
	response, err := g.c.GetExecutorState(ctx, proto.FromShardDistributorGetExecutorStateRequest(gp1), p1...)
	return proto.ToShardDistributorGetExecutorStateResponse(response), proto.ToError(err)
}

func (g sharddistributorClient) GetNamespaceState(ctx context.Context, gp1 *types.GetNamespaceStateRequest, p1 ...yarpc.CallOption) (gp2 *types.GetNamespaceStateResponse, err error) {
	response, err := g.c.GetNamespaceState(ctx, proto.FromShardDistributorGetNamespaceStateRequest(gp1), p1...)
	return proto.ToShardDistributorGetNamespaceStateResponse(response), proto.ToError(err)
}

func (g sharddistributorClient) GetShardOwner(ctx context.Context, gp1 *types.GetShardOwnerRequest, p1 ...yarpc.CallOption) (gp2 *types.GetShardOwnerResponse, err error) {
	response, err := g.c.GetShardOwner(ctx, proto.FromShardDistributorGetShardOwnerRequest(gp1), p1...)
	return proto.ToShardDistributorGetShardOwnerResponse(response), proto.ToError(err)
}

func (g sharddistributorClient) InspectShard(ctx context.Context, gp1 *types.GetShardOwnerRequest, p1 ...yarpc.CallOption) (gp2 *types.GetShardOwnerResponse, err error) {
	response, err := g.c.InspectShard(ctx, proto.FromShardDistributorInspectShardRequest(gp1), p1...)
	return proto.ToShardDistributorInspectShardResponse(response), proto.ToError(err)
}

func (g sharddistributorClient) ListNamespaces(ctx context.Context, lp1 *types.ListNamespacesRequest, p1 ...yarpc.CallOption) (lp2 *types.ListNamespacesResponse, err error) {
	response, err := g.c.ListNamespaces(ctx, proto.FromShardDistributorListNamespacesRequest(lp1), p1...)
	return proto.ToShardDistributorListNamespacesResponse(response), proto.ToError(err)
}

func (g sharddistributorClient) UndrainShards(ctx context.Context, up1 *types.UndrainShardsRequest, p1 ...yarpc.CallOption) (up2 *types.UndrainShardsResponse, err error) {
	response, err := g.c.UndrainShards(ctx, proto.FromShardDistributorUndrainShardsRequest(up1), p1...)
	return proto.ToShardDistributorUndrainShardsResponse(response), proto.ToError(err)
}

func (g sharddistributorClient) WatchNamespaceState(ctx context.Context, wp1 *types.WatchNamespaceStateRequest, p1 ...yarpc.CallOption) (w1 sharddistributor.WatchNamespaceStateClient, err error) {
	stream, err := g.c.WatchNamespaceState(ctx, proto.FromShardDistributorWatchNamespaceStateRequest(wp1), p1...)
	if err != nil {
		return nil, proto.ToError(err)
	}
	return &watchnamespacestateClient{stream: stream}, nil
}

type watchnamespacestateClient struct {
	stream sharddistributorv1.ShardDistributorAPIServiceWatchNamespaceStateYARPCClient
}

func (c *watchnamespacestateClient) Context() context.Context {
	return c.stream.Context()
}

func (c *watchnamespacestateClient) Recv(options ...yarpc.StreamOption) (*types.WatchNamespaceStateResponse, error) {
	response, err := c.stream.Recv(options...)
	if err != nil {
		return nil, proto.ToError(err)
	}
	return proto.ToShardDistributorWatchNamespaceStateResponse(response), nil
}

func (c *watchnamespacestateClient) CloseSend(options ...yarpc.StreamOption) error {
	return proto.ToError(c.stream.CloseSend(options...))
}
