// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -package sharddistributor -source interface.go -destination interface_mock.go -self_package github.com/cadence-workflow/shard-manager/client/sharddistributor
//

// Package sharddistributor is a generated GoMock package.
package sharddistributor

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	yarpc "go.uber.org/yarpc"

	types "github.com/cadence-workflow/shard-manager/common/types"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// DrainShards mocks base method.
func (m *MockClient) DrainShards(arg0 context.Context, arg1 *types.DrainShardsRequest, arg2 ...yarpc.CallOption) (*types.DrainShardsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DrainShards", varargs...)
	ret0, _ := ret[0].(*types.DrainShardsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DrainShards indicates an expected call of DrainShards.
func (mr *MockClientMockRecorder) DrainShards(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DrainShards", reflect.TypeOf((*MockClient)(nil).DrainShards), varargs...)
}

// GetDrainedShards mocks base method.
func (m *MockClient) GetDrainedShards(arg0 context.Context, arg1 *types.GetDrainedShardsRequest, arg2 ...yarpc.CallOption) (*types.GetDrainedShardsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetDrainedShards", varargs...)
	ret0, _ := ret[0].(*types.GetDrainedShardsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDrainedShards indicates an expected call of GetDrainedShards.
func (mr *MockClientMockRecorder) GetDrainedShards(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDrainedShards", reflect.TypeOf((*MockClient)(nil).GetDrainedShards), varargs...)
}

// GetNamespaceState mocks base method.
func (m *MockClient) GetNamespaceState(arg0 context.Context, arg1 *types.GetNamespaceStateRequest, arg2 ...yarpc.CallOption) (*types.GetNamespaceStateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetNamespaceState", varargs...)
	ret0, _ := ret[0].(*types.GetNamespaceStateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNamespaceState indicates an expected call of GetNamespaceState.
func (mr *MockClientMockRecorder) GetNamespaceState(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNamespaceState", reflect.TypeOf((*MockClient)(nil).GetNamespaceState), varargs...)
}

// GetShardOwner mocks base method.
func (m *MockClient) GetShardOwner(arg0 context.Context, arg1 *types.GetShardOwnerRequest, arg2 ...yarpc.CallOption) (*types.GetShardOwnerResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetShardOwner", varargs...)
	ret0, _ := ret[0].(*types.GetShardOwnerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShardOwner indicates an expected call of GetShardOwner.
func (mr *MockClientMockRecorder) GetShardOwner(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShardOwner", reflect.TypeOf((*MockClient)(nil).GetShardOwner), varargs...)
}

// InspectShard mocks base method.
func (m *MockClient) InspectShard(arg0 context.Context, arg1 *types.GetShardOwnerRequest, arg2 ...yarpc.CallOption) (*types.GetShardOwnerResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "InspectShard", varargs...)
	ret0, _ := ret[0].(*types.GetShardOwnerResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InspectShard indicates an expected call of InspectShard.
func (mr *MockClientMockRecorder) InspectShard(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InspectShard", reflect.TypeOf((*MockClient)(nil).InspectShard), varargs...)
}

// UndrainShards mocks base method.
func (m *MockClient) UndrainShards(arg0 context.Context, arg1 *types.UndrainShardsRequest, arg2 ...yarpc.CallOption) (*types.UndrainShardsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UndrainShards", varargs...)
	ret0, _ := ret[0].(*types.UndrainShardsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UndrainShards indicates an expected call of UndrainShards.
func (mr *MockClientMockRecorder) UndrainShards(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UndrainShards", reflect.TypeOf((*MockClient)(nil).UndrainShards), varargs...)
}

// WatchNamespaceState mocks base method.
func (m *MockClient) WatchNamespaceState(arg0 context.Context, arg1 *types.WatchNamespaceStateRequest, arg2 ...yarpc.CallOption) (WatchNamespaceStateClient, error) {
	m.ctrl.T.Helper()
	varargs := []any{arg0, arg1}
	for _, a := range arg2 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WatchNamespaceState", varargs...)
	ret0, _ := ret[0].(WatchNamespaceStateClient)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WatchNamespaceState indicates an expected call of WatchNamespaceState.
func (mr *MockClientMockRecorder) WatchNamespaceState(arg0, arg1 any, arg2 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{arg0, arg1}, arg2...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WatchNamespaceState", reflect.TypeOf((*MockClient)(nil).WatchNamespaceState), varargs...)
}

// MockWatchNamespaceStateClient is a mock of WatchNamespaceStateClient interface.
type MockWatchNamespaceStateClient struct {
	ctrl     *gomock.Controller
	recorder *MockWatchNamespaceStateClientMockRecorder
	isgomock struct{}
}

// MockWatchNamespaceStateClientMockRecorder is the mock recorder for MockWatchNamespaceStateClient.
type MockWatchNamespaceStateClientMockRecorder struct {
	mock *MockWatchNamespaceStateClient
}

// NewMockWatchNamespaceStateClient creates a new mock instance.
func NewMockWatchNamespaceStateClient(ctrl *gomock.Controller) *MockWatchNamespaceStateClient {
	mock := &MockWatchNamespaceStateClient{ctrl: ctrl}
	mock.recorder = &MockWatchNamespaceStateClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatchNamespaceStateClient) EXPECT() *MockWatchNamespaceStateClientMockRecorder {
	return m.recorder
}

// CloseSend mocks base method.
func (m *MockWatchNamespaceStateClient) CloseSend(arg0 ...yarpc.StreamOption) error {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CloseSend", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseSend indicates an expected call of CloseSend.
func (mr *MockWatchNamespaceStateClientMockRecorder) CloseSend(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseSend", reflect.TypeOf((*MockWatchNamespaceStateClient)(nil).CloseSend), arg0...)
}

// Context mocks base method.
func (m *MockWatchNamespaceStateClient) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockWatchNamespaceStateClientMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockWatchNamespaceStateClient)(nil).Context))
}

// Recv mocks base method.
func (m *MockWatchNamespaceStateClient) Recv(arg0 ...yarpc.StreamOption) (*types.WatchNamespaceStateResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range arg0 {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Recv", varargs...)
	ret0, _ := ret[0].(*types.WatchNamespaceStateResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Recv indicates an expected call of Recv.
func (mr *MockWatchNamespaceStateClientMockRecorder) Recv(arg0 ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Recv", reflect.TypeOf((*MockWatchNamespaceStateClient)(nil).Recv), arg0...)
}
