// Code generated by protoc-gen-yarpc-go. DO NOT EDIT.
// source: uber/cadence/sharddistributor/v1/canary.proto

package sharddistributorv1

import (
	"context"
	"io/ioutil"
	"reflect"

	"github.com/gogo/protobuf/jsonpb"
	"github.com/gogo/protobuf/proto"
	"go.uber.org/fx"
	"go.uber.org/yarpc"
	"go.uber.org/yarpc/api/transport"
	"go.uber.org/yarpc/api/x/restriction"
	"go.uber.org/yarpc/encoding/protobuf"
	"go.uber.org/yarpc/encoding/protobuf/reflection"
)

var _ = ioutil.NopCloser

// ShardDistributorExecutorCanaryAPIYARPCClient is the YARPC client-side interface for the ShardDistributorExecutorCanaryAPI service.
type ShardDistributorExecutorCanaryAPIYARPCClient interface {
	Ping(context.Context, *PingRequest, ...yarpc.CallOption) (*PingResponse, error)
}

func newShardDistributorExecutorCanaryAPIYARPCClient(clientConfig transport.ClientConfig, anyResolver jsonpb.AnyResolver, options ...protobuf.ClientOption) ShardDistributorExecutorCanaryAPIYARPCClient {
	return &_ShardDistributorExecutorCanaryAPIYARPCCaller{protobuf.NewStreamClient(
		protobuf.ClientParams{
			ServiceName:  "uber.cadence.sharddistributor.v1.ShardDistributorExecutorCanaryAPI",
			ClientConfig: clientConfig,
			AnyResolver:  anyResolver,
			Options:      options,
		},
	)}
}

// NewShardDistributorExecutorCanaryAPIYARPCClient builds a new YARPC client for the ShardDistributorExecutorCanaryAPI service.
func NewShardDistributorExecutorCanaryAPIYARPCClient(clientConfig transport.ClientConfig, options ...protobuf.ClientOption) ShardDistributorExecutorCanaryAPIYARPCClient {
	return newShardDistributorExecutorCanaryAPIYARPCClient(clientConfig, nil, options...)
}

// ShardDistributorExecutorCanaryAPIYARPCServer is the YARPC server-side interface for the ShardDistributorExecutorCanaryAPI service.
type ShardDistributorExecutorCanaryAPIYARPCServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
}

type buildShardDistributorExecutorCanaryAPIYARPCProceduresParams struct {
	Server      ShardDistributorExecutorCanaryAPIYARPCServer
	AnyResolver jsonpb.AnyResolver
}

func buildShardDistributorExecutorCanaryAPIYARPCProcedures(params buildShardDistributorExecutorCanaryAPIYARPCProceduresParams) []transport.Procedure {
	handler := &_ShardDistributorExecutorCanaryAPIYARPCHandler{params.Server}
	return protobuf.BuildProcedures(
		protobuf.BuildProceduresParams{
			ServiceName: "uber.cadence.sharddistributor.v1.ShardDistributorExecutorCanaryAPI",
			UnaryHandlerParams: []protobuf.BuildProceduresUnaryHandlerParams{
				{
					MethodName: "Ping",
					Handler: protobuf.NewUnaryHandler(
						protobuf.UnaryHandlerParams{
							Handle:      handler.Ping,
							NewRequest:  newShardDistributorExecutorCanaryAPIServicePingYARPCRequest,
							AnyResolver: params.AnyResolver,
						},
					),
				},
			},
			OnewayHandlerParams: []protobuf.BuildProceduresOnewayHandlerParams{},
			StreamHandlerParams: []protobuf.BuildProceduresStreamHandlerParams{},
		},
	)
}

// BuildShardDistributorExecutorCanaryAPIYARPCProcedures prepares an implementation of the ShardDistributorExecutorCanaryAPI service for YARPC registration.
func BuildShardDistributorExecutorCanaryAPIYARPCProcedures(server ShardDistributorExecutorCanaryAPIYARPCServer) []transport.Procedure {
	return buildShardDistributorExecutorCanaryAPIYARPCProcedures(buildShardDistributorExecutorCanaryAPIYARPCProceduresParams{Server: server})
}

// FxShardDistributorExecutorCanaryAPIYARPCClientParams defines the input
// for NewFxShardDistributorExecutorCanaryAPIYARPCClient. It provides the
// paramaters to get a ShardDistributorExecutorCanaryAPIYARPCClient in an
// Fx application.
type FxShardDistributorExecutorCanaryAPIYARPCClientParams struct {
	fx.In

	Provider    yarpc.ClientConfig
	AnyResolver jsonpb.AnyResolver  `name:"yarpcfx" optional:"true"`
	Restriction restriction.Checker `optional:"true"`
}

// FxShardDistributorExecutorCanaryAPIYARPCClientResult defines the output
// of NewFxShardDistributorExecutorCanaryAPIYARPCClient. It provides a
// ShardDistributorExecutorCanaryAPIYARPCClient to an Fx application.
type FxShardDistributorExecutorCanaryAPIYARPCClientResult struct {
	fx.Out

	Client ShardDistributorExecutorCanaryAPIYARPCClient

	// We are using an fx.Out struct here instead of just returning a client
	// so that we can add more values or add named versions of the client in
	// the future without breaking any existing code.
}

// NewFxShardDistributorExecutorCanaryAPIYARPCClient provides a ShardDistributorExecutorCanaryAPIYARPCClient
// to an Fx application using the given name for routing.
//
//	fx.Provide(
//	  sharddistributorv1.NewFxShardDistributorExecutorCanaryAPIYARPCClient("service-name"),
//	  ...
//	)
func NewFxShardDistributorExecutorCanaryAPIYARPCClient(name string, options ...protobuf.ClientOption) interface{} {
	return func(params FxShardDistributorExecutorCanaryAPIYARPCClientParams) FxShardDistributorExecutorCanaryAPIYARPCClientResult {
		cc := params.Provider.ClientConfig(name)

		if params.Restriction != nil {
			if namer, ok := cc.GetUnaryOutbound().(transport.Namer); ok {
				if err := params.Restriction.Check(protobuf.Encoding, namer.TransportName()); err != nil {
					panic(err.Error())
				}
			}
		}

		return FxShardDistributorExecutorCanaryAPIYARPCClientResult{
			Client: newShardDistributorExecutorCanaryAPIYARPCClient(cc, params.AnyResolver, options...),
		}
	}
}

// FxShardDistributorExecutorCanaryAPIYARPCProceduresParams defines the input
// for NewFxShardDistributorExecutorCanaryAPIYARPCProcedures. It provides the
// paramaters to get ShardDistributorExecutorCanaryAPIYARPCServer procedures in an
// Fx application.
type FxShardDistributorExecutorCanaryAPIYARPCProceduresParams struct {
	fx.In

	Server      ShardDistributorExecutorCanaryAPIYARPCServer
	AnyResolver jsonpb.AnyResolver `name:"yarpcfx" optional:"true"`
}

// FxShardDistributorExecutorCanaryAPIYARPCProceduresResult defines the output
// of NewFxShardDistributorExecutorCanaryAPIYARPCProcedures. It provides
// ShardDistributorExecutorCanaryAPIYARPCServer procedures to an Fx application.
//
// The procedures are provided to the "yarpcfx" value group.
// Dig 1.2 or newer must be used for this feature to work.
type FxShardDistributorExecutorCanaryAPIYARPCProceduresResult struct {
	fx.Out

	Procedures     []transport.Procedure `group:"yarpcfx"`
	ReflectionMeta reflection.ServerMeta `group:"yarpcfx"`
}

// NewFxShardDistributorExecutorCanaryAPIYARPCProcedures provides ShardDistributorExecutorCanaryAPIYARPCServer procedures to an Fx application.
// It expects a ShardDistributorExecutorCanaryAPIYARPCServer to be present in the container.
//
//	fx.Provide(
//	  sharddistributorv1.NewFxShardDistributorExecutorCanaryAPIYARPCProcedures(),
//	  ...
//	)
func NewFxShardDistributorExecutorCanaryAPIYARPCProcedures() interface{} {
	return func(params FxShardDistributorExecutorCanaryAPIYARPCProceduresParams) FxShardDistributorExecutorCanaryAPIYARPCProceduresResult {
		return FxShardDistributorExecutorCanaryAPIYARPCProceduresResult{
			Procedures: buildShardDistributorExecutorCanaryAPIYARPCProcedures(buildShardDistributorExecutorCanaryAPIYARPCProceduresParams{
				Server:      params.Server,
				AnyResolver: params.AnyResolver,
			}),
			ReflectionMeta: ShardDistributorExecutorCanaryAPIReflectionMeta,
		}
	}
}

// ShardDistributorExecutorCanaryAPIReflectionMeta is the reflection server metadata
// required for using the gRPC reflection protocol with YARPC.
//
// See https://github.com/grpc/grpc/blob/master/doc/server-reflection.md.
var ShardDistributorExecutorCanaryAPIReflectionMeta = reflection.ServerMeta{
	ServiceName:     "uber.cadence.sharddistributor.v1.ShardDistributorExecutorCanaryAPI",
	FileDescriptors: yarpcFileDescriptorClosure03b11524fa4f4f94,
}

type _ShardDistributorExecutorCanaryAPIYARPCCaller struct {
	streamClient protobuf.StreamClient
}

func (c *_ShardDistributorExecutorCanaryAPIYARPCCaller) Ping(ctx context.Context, request *PingRequest, options ...yarpc.CallOption) (*PingResponse, error) {
	responseMessage, err := c.streamClient.Call(ctx, "Ping", request, newShardDistributorExecutorCanaryAPIServicePingYARPCResponse, options...)
	if responseMessage == nil {
		return nil, err
	}
	response, ok := responseMessage.(*PingResponse)
	if !ok {
		return nil, protobuf.CastError(emptyShardDistributorExecutorCanaryAPIServicePingYARPCResponse, responseMessage)
	}
	return response, err
}

type _ShardDistributorExecutorCanaryAPIYARPCHandler struct {
	server ShardDistributorExecutorCanaryAPIYARPCServer
}

func (h *_ShardDistributorExecutorCanaryAPIYARPCHandler) Ping(ctx context.Context, requestMessage proto.Message) (proto.Message, error) {
	var request *PingRequest
	var ok bool
	if requestMessage != nil {
		request, ok = requestMessage.(*PingRequest)
		if !ok {
			return nil, protobuf.CastError(emptyShardDistributorExecutorCanaryAPIServicePingYARPCRequest, requestMessage)
		}
	}
	response, err := h.server.Ping(ctx, request)
	if response == nil {
		return nil, err
	}
	return response, err
}

func newShardDistributorExecutorCanaryAPIServicePingYARPCRequest() proto.Message {
	return &PingRequest{}
}

func newShardDistributorExecutorCanaryAPIServicePingYARPCResponse() proto.Message {
	return &PingResponse{}
}

var (
	emptyShardDistributorExecutorCanaryAPIServicePingYARPCRequest  = &PingRequest{}
	emptyShardDistributorExecutorCanaryAPIServicePingYARPCResponse = &PingResponse{}
)

var yarpcFileDescriptorClosure03b11524fa4f4f94 = [][]byte{
	// uber/cadence/sharddistributor/v1/canary.proto
	[]byte{
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x3d, 0x4f, 0xc3, 0x30,
		0x10, 0x86, 0x15, 0x40, 0xa8, 0xb9, 0x32, 0x79, 0xaa, 0xf8, 0x10, 0xa5, 0x13, 0x4b, 0x6c, 0x05,
		0x46, 0x26, 0xbe, 0x24, 0x2a, 0x96, 0x2a, 0x6c, 0x20, 0x14, 0x39, 0xce, 0x91, 0x46, 0x21, 0x76,
		0xb0, 0xf3, 0x41, 0xfe, 0x02, 0xbf, 0x1a, 0xc5, 0x49, 0x55, 0x5a, 0x21, 0xc1, 0xfa, 0xf8, 0xd1,
		0xeb, 0xbb, 0x7b, 0xc1, 0xab, 0x22, 0xd4, 0x4c, 0xf0, 0x18, 0xa5, 0x40, 0x66, 0x96, 0x5c, 0xc7,
		0x71, 0x6a, 0x4a, 0x9d, 0x46, 0x55, 0xa9, 0x34, 0xab, 0x7d, 0x26, 0xb8, 0xe4, 0xba, 0xa5, 0x85,
		0x56, 0xa5, 0x22, 0xd3, 0x4e, 0xa7, 0x83, 0x4e, 0xb7, 0x75, 0x5a, 0xfb, 0xb3, 0x07, 0x18, 0x2f,
		0x52, 0x99, 0x04, 0xf8, 0x51, 0xa1, 0x29, 0xc9, 0x11, 0xb8, 0xd6, 0x0a, 0x33, 0x6c, 0x27, 0xce,
		0xd4, 0x39, 0x77, 0x83, 0x91, 0x05, 0x8f, 0xd8, 0x92, 0x63, 0x70, 0x25, 0xcf, 0xd1, 0x14, 0x5c,
		0xe0, 0x64, 0xc7, 0x3e, 0xae, 0xc1, 0x2c, 0x83, 0x83, 0x3e, 0xc9, 0x14, 0x4a, 0x1a, 0x24, 0xa7,
		0x30, 0xc6, 0x4f, 0x14, 0xdd, 0x47, 0x61, 0x1a, 0x0f, 0x61, 0xb0, 0x42, 0xf3, 0x98, 0x9c, 0x00,
		0xa8, 0x46, 0x9a, 0xd0, 0xe6, 0xdb, 0xbc, 0x51, 0xe0, 0x76, 0xe4, 0xa9, 0x03, 0x9b, 0xa3, 0xec,
		0x6e, 0x8e, 0x72, 0xf1, 0xe5, 0xc0, 0x99, 0xd5, 0xee, 0xd6, 0xeb, 0xdc, 0x0f, 0xd1, 0xb7, 0xf6,
		0x02, 0xd7, 0x8b, 0x39, 0x41, 0xd8, 0xeb, 0x46, 0x22, 0x1e, 0xfd, 0xeb, 0x0e, 0xf4, 0xc7, 0x11,
		0x0e, 0xe9, 0x7f, 0xf5, 0x7e, 0xd3, 0x9b, 0xd7, 0xe7, 0x97, 0x24, 0x2d, 0x97, 0x55, 0x44, 0x85,
		0xca, 0x57, 0xe5, 0x78, 0x8d, 0xd2, 0xd9, 0xdb, 0xbb, 0x6a, 0xfa, 0x96, 0xbc, 0x9c, 0x4b, 0x9e,
		0xa0, 0x66, 0x34, 0x41, 0xc9, 0x6c, 0x3b, 0xbf, 0xd5, 0x77, 0xb5, 0xcd, 0x6a, 0x3f, 0xda, 0xb7,
		0xf6, 0xe5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x09, 0x81, 0xdf, 0x7c, 0xfc, 0x01, 0x00, 0x00,
	},
}

func init() {
	yarpc.RegisterClientBuilder(
		func(clientConfig transport.ClientConfig, structField reflect.StructField) ShardDistributorExecutorCanaryAPIYARPCClient {
			return NewShardDistributorExecutorCanaryAPIYARPCClient(clientConfig, protobuf.ClientBuilderOptions(clientConfig, structField)...)
		},
	)
}
